### ISSUE TITLE
Wink and a nudge

### ISSUE THREAD

**Issue by Bazmundi** [alexyu132/fusebox3#2]
Frame dimensions: ?348x?370xH426mm

Understanding Alex knows but others may not without investigation, can we update info with width and depth?

**Comment by alexyu132** [comment]
Hi, sorry for the late response - I was originally planning to build a prototype of this design last year, but ended up postponing that, and am aiming to get one of these built in the next few months. I just pushed a few updates to the design, adjusting some of the extrusion lengths for a bit of extra X/Y travel and increasing belt/idler clearances.

The new dimensions are 350x372x427mm (X,Y,Z).
