### ISSUE TITLE
bed assembly

### ISSUE THREAD

**Issue by nsdf7** [alexyu132/fusebox3#4]
have this machine built and working great. for the BOM i'd suggest M4x55 or 60 screws and longer springs. this is the only issue i ran into.

**Comment by alexyu132** [comment]
Thanks for the info, got a link to those springs? And how close is your bed to the z platform extrusions? On mine I've lowered the gap as much as possible to make sure it has the max possible build area

**Comment by nsdf7** [comment]
Here's the springs I used.

MroMax 3D Printer Die Spring 8mm...
https://www.amazon.com/dp/B07YYXN387?ref=ppx_pop_mob_ap_share

Bed to extrusion is about 10mm, I wanted to leave some room allow for
heated insulation.

**Comment by alexyu132** [comment]
Thanks, updated the BOM with recommendation
